# Generated by Django 4.2.9 on 2024-07-17 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='question')),
                ('answer', models.TextField(blank=True, verbose_name='réponse')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('formation', 'Formation'), ('ebook', 'Livres'), ('about', "À propos de l'activité")], max_length=20, verbose_name='Catégorie de Faq')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'question reponse',
                'ordering': ['-created_at'],
            },
        ),
    ]
