# Generated by Django 4.2.9 on 2024-01-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faqcategory_faq_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.faqcategory', verbose_name='Catégorie'),
        ),
    ]
