# Generated by Django 4.2.9 on 2024-01-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_faq_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Catégorie de question'},
        ),
    ]
