# Generated by Django 4.2.9 on 2024-01-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_faqcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foire aux question'},
        ),
    ]
