# Generated by Django 4.2.9 on 2024-01-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categorymodel_options_categorymodel_created_at_and_more'),
        ('faq', '0006_alter_faq_options_alter_faqcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorymodel', verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='FaqCategory',
        ),
    ]
