# Generated by Django 4.2.9 on 2024-02-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categorymodel_options'),
        ('faq', '0007_alter_faq_faq_category_delete_faqcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('formation', 'Formation'), ('ebook', 'Livres'), ('about', "À propos de l'activité")], default='formation', max_length=20, verbose_name='Catégorie de Faq'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorymodel', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, unique=True, verbose_name='question'),
        ),
    ]
