# Generated by Django 4.2.9 on 2024-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0010_remove_faq_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
