# Generated by Django 4.2.9 on 2024-02-19 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0011_alter_faq_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='FaqModel',
        ),
    ]
