# Generated by Django 4.2.9 on 2024-05-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0012_rename_faq_faqmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'question reponse'},
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
    ]
