# Generated by Django 4.2.9 on 2024-07-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du visiteur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse mail du visiteur')),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('content', models.TextField(max_length=255, verbose_name='Contenu du message')),
            ],
            options={
                'verbose_name': "Message d'un visiteur",
                'verbose_name_plural': 'Messages des visiteurs',
            },
        ),
    ]
