# Generated by Django 4.2.9 on 2024-01-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': "Message d'un visiteur", 'verbose_name_plural': 'Messages des visiteurs'},
        ),
    ]
