# Generated by Django 4.2.9 on 2024-04-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitevideomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitevideomodel',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
