# Generated by Django 4.2.9 on 2024-04-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevideomodel',
            name='show_where',
            field=models.CharField(choices=[('home', 'Accueil'), ('formations', 'Formations'), ('formation', 'Détails des formations'), ('ebooks', 'Ebooks'), ('ebook', 'Détails des ebooks'), ('events', 'Évènements'), ('event', 'Détail des évènements'), ('faq', 'Foire aux questions'), ('about', 'À propos'), ('blog', 'Blog'), ('post', 'Post')], default='home', max_length=15, verbose_name='Où afficher ?'),
        ),
        migrations.AlterField(
            model_name='sitevideomodel',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='titre de la vidéo'),
        ),
        migrations.AlterField(
            model_name='sitevideomodel',
            name='video',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='identifiant YouTube de la vidéo'),
        ),
    ]
