# Generated by Django 4.2.9 on 2024-04-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitevideomodel_show_where_alter_sitevideomodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevideomodel',
            name='show_where',
            field=models.CharField(choices=[('home', 'Accueil'), ('formations', 'Formations'), ('formation', 'Détails des formations'), ('ebooks', 'Ebooks'), ('ebook', 'Détails des ebooks'), ('events', 'Évènements'), ('event', 'Détail des évènements'), ('faq', 'Foire aux questions'), ('about', 'À propos'), ('blog', 'Blog'), ('post', 'Post')], default='home', max_length=15, verbose_name='Afficher où ?'),
        ),
    ]
