# Generated by Django 4.2.9 on 2024-06-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='is_subscrib',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='newsletter.subscribers', verbose_name='abonné(e)'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribers_group',
            field=models.ManyToManyField(blank=True, related_name='subscribers_group', to='newsletter.subscribersgroup', verbose_name="groupe d'abonné(e)"),
        ),
    ]
