# Generated by Django 4.2.9 on 2024-01-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-created_at'], 'verbose_name': 'Témoignage'},
        ),
        migrations.AlterField(
            model_name='testimony',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du témoignage'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
