# Generated by Django 4.2.9 on 2024-02-15 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimony', '0004_testimony_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Contenu')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Est-ce visible sur le site ?')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Modifié le')),
                ('created_at', models.DateField(auto_now=True, null=True, verbose_name='Créé le')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du témoignage')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
