# Generated by Django 4.2.9 on 2024-06-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0005_testimonymodel_delete_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonymodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'témoignage', 'verbose_name_plural': 'témoignages'},
        ),
    ]
