# Generated by Django 4.2.9 on 2024-06-23 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimony', '0006_alter_testimonymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonymodel',
            name='rate',
            field=models.CharField(choices=[(0, 'Très mécontent'), (1, 'Mécontent'), (2, 'Indifférent'), (3, 'Satisfait'), (4, 'Très Satisfait')], default=4, max_length=10, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auteur du témoignage'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='content',
            field=models.TextField(max_length=500, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='created_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='est-ce visible sur le site ?'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='modifié le'),
        ),
    ]
