# Generated by Django 4.2.9 on 2024-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0007_testimonymodel_rate_alter_testimonymodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonymodel',
            name='rate',
            field=models.IntegerField(choices=[(0, 'Très mécontent'), (1, 'Mécontent'), (2, 'Indifférent'), (3, 'Satisfait'), (4, 'Très Satisfait')], default=4, verbose_name='note'),
        ),
    ]
