# Generated by Django 4.2.9 on 2024-06-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimony', '0008_alter_testimonymodel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonymodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='testimonymodel',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='publié ?'),
        ),
    ]
