# Generated by Django 4.2.9 on 2024-08-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('formation', '0001_initial'),
        ('profil', '0001_initial'),
        ('ebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de publication')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=255, verbose_name='texte présentatif')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=5000000, verbose_name='contenu')),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d', verbose_name="image d'illustration")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auteur de la publication')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categorymodel', verbose_name='catégorie de la publication')),
                ('high_light_ebooks', models.ManyToManyField(blank=True, related_name='high_light_ebooks', to='ebook.ebookmodel', verbose_name='livres mis en avant')),
                ('high_light_formations', models.ManyToManyField(blank=True, related_name='high_light_formations', to='formation.formation', verbose_name='formations mises en avant')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('content', models.TextField(max_length=500, verbose_name='contenu')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.userprofilmodel', verbose_name='auteur')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost', verbose_name='publication')),
                ('reply_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcomment', verbose_name='réponse de')),
            ],
            options={
                'verbose_name': 'commentaire de post',
                'verbose_name_plural': 'commentaires de post',
            },
        ),
    ]
