# Generated by Django 4.2.9 on 2024-02-05 04:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Contenu'),
        ),
    ]
