# Generated by Django 4.2.9 on 2024-04-08 01:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=5000000, verbose_name='Contenu'),
        ),
    ]
