# Generated by Django 4.2.9 on 2024-05-13 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitevideomodel_show_where'),
        ('blog', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categorymodel', verbose_name='Catégorie de la publication'),
        ),
    ]
