# Generated by Django 4.2.9 on 2024-06-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_userprofilmodel_user'),
        ('blog', '0008_alter_blogcomment_options_alter_blogcomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.userprofilmodel', verbose_name='auteur'),
        ),
    ]
