# Generated by Django 4.2.9 on 2024-06-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogcomment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='replies',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reply_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcomment', verbose_name='réponse de'),
        ),
    ]
