# Generated by Django 4.2.9 on 2024-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0020_alter_videocomment_options_and_more'),
        ('ebook', '0013_saleebook_buy_version'),
        ('blog', '0011_alter_blogpost_options_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='high_light_ebooks',
            field=models.ManyToManyField(blank=True, related_name='high_light_formations', to='ebook.ebookmodel', verbose_name='Livres mis en avant'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='high_light_formations',
            field=models.ManyToManyField(blank=True, related_name='high_light_formations', to='formation.formation', verbose_name='Formations mis en avant'),
        ),
    ]
