# Generated by Django 4.2.9 on 2024-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0021_physicformationcmd'),
        ('ebook', '0013_saleebook_buy_version'),
        ('blog', '0012_blogpost_high_light_ebooks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='high_light_ebooks',
            field=models.ManyToManyField(blank=True, related_name='high_light_ebooks', to='ebook.ebookmodel', verbose_name='livres mis en avant'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='high_light_formations',
            field=models.ManyToManyField(blank=True, related_name='high_light_formations', to='formation.formation', verbose_name='formations mis en avant'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='illustration_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d', verbose_name="image d'illustration"),
        ),
    ]
