# Generated by Django 4.2.9 on 2024-07-17 08:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titre')),
                ('subtitle', models.CharField(default='', max_length=255, verbose_name='texte présentatif')),
                ('description', tinymce.models.HTMLField(max_length=5000000, verbose_name='description de la formation')),
                ('start_at', models.DateTimeField(null=True, verbose_name='date de debut')),
                ('end_at', models.DateTimeField(null=True, verbose_name='date de fin')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('show_at_home', models.BooleanField(default=False, verbose_name="afficher à l'accueil")),
                ('illustration_image', models.ImageField(upload_to='images/events/%Y/%m/%d', verbose_name="image d'illustration")),
                ('illustration_video', models.CharField(blank=True, max_length=20, null=True, verbose_name="Identifiant de la vidéo d'illustration")),
                ('inscription_link', models.CharField(blank=True, max_length=355, null=True, verbose_name="lien d'inscription")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorymodel', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'évènement',
                'verbose_name_plural': 'évènements',
            },
        ),
    ]
