# Generated by Django 4.2.9 on 2024-02-29 01:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=tinymce.models.HTMLField(max_length=50000, verbose_name='description de la formation'),
        ),
    ]
