# Generated by Django 4.2.9 on 2024-04-08 01:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=tinymce.models.HTMLField(max_length=5000000, verbose_name='description de la formation'),
        ),
    ]
