# Generated by Django 4.2.9 on 2024-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventmodel_show_at_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
