# Generated by Django 4.2.9 on 2024-02-05 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_categorymodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('description', models.TextField(max_length=20000, verbose_name='description de la formation')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d', verbose_name="Image d'illustration")),
                ('illustration_video', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Lien de la vidéo d'illustration")),
                ('normal_price', models.FloatField(verbose_name='Prix normal')),
                ('promo_price', models.FloatField(verbose_name='Prix promotionnel')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorymodel', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='FormationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre de la vidéo')),
                ('decription', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lien de la vidéo')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Vidéo de formation',
                'verbose_name_plural': 'Vidéos de formation',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('content', models.TextField(max_length=200, verbose_name='Contenu')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('replies', models.ManyToManyField(blank=True, related_name='responses', to='formation.videocomment')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.formationvideo', verbose_name='Vidéo')),
            ],
            options={
                'verbose_name': 'Commentaire de vidéo',
                'verbose_name_plural': 'Commentaires de vidéo',
            },
        ),
        migrations.CreateModel(
            name='SaleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'achat")),
                ('isPaid', models.BooleanField(default=False, verbose_name='Payé ?')),
                ('amount', models.FloatField(verbose_name='Montant facturé')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.formation', verbose_name='Livre acheté')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acheté par')),
            ],
            options={
                'verbose_name': 'Formation vendue',
                'verbose_name_plural': 'Formations vendues',
            },
        ),
    ]
