# Generated by Django 4.2.9 on 2024-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicformationcmd',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='payé?'),
        ),
    ]
