# Generated by Django 4.2.9 on 2024-02-05 04:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_formation_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=tinymce.models.HTMLField(max_length=20000, verbose_name='description de la formation'),
        ),
        migrations.AlterField(
            model_name='formationvideo',
            name='decription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='content',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='Contenu'),
        ),
    ]
