# Generated by Django 4.2.9 on 2024-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_physicformationcmd_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre de la vidéo'),
        ),
    ]
