# Generated by Django 4.2.9 on 2024-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_formation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Texte présentatif'),
        ),
    ]
