# Generated by Django 4.2.9 on 2024-02-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_formation_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='illustration_image',
            field=models.ImageField(upload_to='images/formation/%Y/%m/%d', verbose_name="Image d'illustration"),
        ),
    ]
