# Generated by Django 4.2.9 on 2024-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_alter_formation_illustration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='course_duration',
            field=models.IntegerField(default=135, verbose_name='Durée totale des cours (en minutes)'),
        ),
    ]
