# Generated by Django 4.2.9 on 2024-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_formation_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='course_duration',
            field=models.IntegerField(verbose_name='Durée totale des cours (en minutes)'),
        ),
    ]
