# Generated by Django 4.2.9 on 2024-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_alter_formation_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationvideo',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formationvideo',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Identifiant de la vidéo'),
        ),
    ]
