# Generated by Django 4.2.9 on 2024-03-25 23:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_alter_formationvideo_decription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationvideo',
            name='decription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Contenu'),
        ),
    ]
