# Generated by Django 4.2.9 on 2024-04-07 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0009_alter_formationvideo_decription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleformation',
            options={'verbose_name': 'formation vendue', 'verbose_name_plural': 'formations vendues'},
        ),
        migrations.AlterField(
            model_name='saleformation',
            name='amount',
            field=models.FloatField(verbose_name='montant facturé'),
        ),
        migrations.AlterField(
            model_name='saleformation',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="date d'achat"),
        ),
        migrations.AlterField(
            model_name='saleformation',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.formation', verbose_name='livre acheté'),
        ),
        migrations.AlterField(
            model_name='saleformation',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='payé ?'),
        ),
        migrations.AlterField(
            model_name='saleformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='acheté par'),
        ),
    ]
