# Generated by Django 4.2.9 on 2024-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_alter_formation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='illustration_video',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Identifiant de la vidéo d'illustration"),
        ),
        migrations.AlterField(
            model_name='formationvideo',
            name='video',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identifiant de la vidéo'),
        ),
    ]
