# Generated by Django 4.2.9 on 2024-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_alter_formation_illustration_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='course_duration',
            field=models.IntegerField(verbose_name='Durée totale des cours (en heures)'),
        ),
    ]
