# Generated by Django 4.2.9 on 2024-05-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_alter_formation_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='normal_price',
            field=models.FloatField(verbose_name='Prix barré'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='promo_price',
            field=models.FloatField(verbose_name='Prix de vente'),
        ),
    ]
