# Generated by Django 4.2.9 on 2024-05-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_alter_formation_normal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationvideo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
