# Generated by Django 4.2.9 on 2024-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0015_alter_formationvideo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationvideo',
            name='order',
            field=models.IntegerField(auto_created=True, default=1, verbose_name="Ordre d'affichage de la vidéo"),
        ),
        migrations.AlterField(
            model_name='formationvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
