# Generated by Django 4.2.9 on 2024-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0017_alter_saleformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationvideo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
