# Generated by Django 4.2.9 on 2024-02-05 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_categorymodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre du livre')),
                ('description', models.TextField(max_length=20000, verbose_name='description du livre')),
                ('ebook_file', models.FileField(blank=True, null=True, upload_to='ebook/pdf/%Y/%m/%d', validators=[ebook.models.validate_pdf_file], verbose_name='Livre au format pdf')),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to='images/ebook/%Y/%m/%d', verbose_name="Image d'illustration")),
                ('illustration_video', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Lien vers la vidéo d'illustration")),
                ('normal_price', models.FloatField(verbose_name='Prix normal du livre')),
                ('promo_price', models.FloatField(verbose_name='Prix promotionnel')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorymodel', verbose_name='Catégorie du livre')),
            ],
            options={
                'verbose_name': 'E-book',
                'verbose_name_plural': 'E-books',
            },
        ),
        migrations.CreateModel(
            name='SaleEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'achat")),
                ('isPaid', models.BooleanField(default=False, verbose_name='Payé ?')),
                ('amount', models.FloatField(verbose_name='Montant facturé')),
                ('ebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebook.ebookmodel', verbose_name='Livre acheté')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acheté par')),
            ],
            options={
                'verbose_name': 'Livre vendu',
                'verbose_name_plural': 'Livres vendus',
            },
        ),
    ]
