# Generated by Django 4.2.9 on 2024-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='subtitle',
            field=models.TextField(default='', max_length=255, verbose_name='Texte présentatif'),
        ),
    ]
