# Generated by Django 4.2.9 on 2024-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_alter_ebookmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookmodel',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Texte présentatif'),
        ),
    ]
