# Generated by Django 4.2.9 on 2024-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_alter_ebookmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='availability',
            field=models.CharField(choices=[('numeric', 'Uniquement la version physique'), ('physic', 'Uniquement la version numérique'), ('both', 'Version physique et numerique disponibles')], default='both', max_length=10, verbose_name='Version disponible'),
        ),
    ]
