# Generated by Django 4.2.9 on 2024-05-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0008_alter_ebookmodel_illustration_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookmodel',
            name='normal_price',
            field=models.FloatField(verbose_name='Prix barré'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='promo_price',
            field=models.FloatField(verbose_name='Prix de vente'),
        ),
    ]
