# Generated by Django 4.2.9 on 2024-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0009_alter_ebookmodel_normal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
