# Generated by Django 4.2.9 on 2024-06-23 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebook', '0010_ebookmodel_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebookmodel',
            options={'verbose_name': 'e-book', 'verbose_name_plural': 'e-books'},
        ),
        migrations.AlterModelOptions(
            name='saleebook',
            options={'verbose_name': 'livre vendu', 'verbose_name_plural': 'livres vendus'},
        ),
        migrations.AddField(
            model_name='saleebook',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='saleebook',
            name='my_reference',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='ma reference'),
        ),
        migrations.AddField(
            model_name='saleebook',
            name='notch_pay_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reference de notchpay'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='availability',
            field=models.CharField(choices=[('numeric', 'Uniquement la version physique'), ('physic', 'Uniquement la version numérique'), ('both', 'Version physique et numerique disponibles')], default='both', max_length=10, verbose_name='version disponible'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='illustration_video',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="identifiant vers la vidéo d'illustration"),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='normal_price',
            field=models.FloatField(verbose_name='prix barré'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='promo_price',
            field=models.FloatField(verbose_name='prix de vente/facturé'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='published',
            field=models.BooleanField(default=True, verbose_name='publié'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='titre du livre'),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='amount',
            field=models.FloatField(verbose_name='montant facturé'),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="date d'achat"),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='ebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebook.ebookmodel', verbose_name='livre acheté'),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='payé ?'),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='acheté par'),
        ),
    ]
