# Generated by Django 4.2.9 on 2024-06-23 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0011_alter_ebookmodel_options_alter_saleebook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleebook',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='le status du paiement'),
        ),
        migrations.AlterField(
            model_name='saleebook',
            name='my_reference',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='reference de la transaction'),
        ),
    ]
