# Generated by Django 4.2.9 on 2024-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0012_saleebook_status_alter_saleebook_my_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleebook',
            name='buy_version',
            field=models.CharField(choices=[('numeric', 'Uniquement la version physique'), ('physic', 'Uniquement la version numérique')], default='numeric', max_length=10, verbose_name='version achetée'),
        ),
    ]
