# Generated by Django 4.2.9 on 2024-07-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0013_saleebook_buy_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicEbookCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="date d'achat")),
                ('isPaid', models.BooleanField(default=False, verbose_name='payé ?')),
                ('amount', models.FloatField(verbose_name='montant facturé')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone client')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('ebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebook.ebookmodel', verbose_name='livre acheté')),
            ],
            options={
                'verbose_name': 'commande physique',
                'verbose_name_plural': 'commandes physiques',
            },
        ),
    ]
