# Generated by Django 4.2.9 on 2024-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0014_physicebookcmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicebookcmd',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de commande'),
        ),
    ]
