# Generated by Django 4.2.9 on 2024-06-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('created_at', models.DateField(auto_now=True, null=True, verbose_name='créé le')),
                ('profil_image', models.ImageField(blank=True, null=True, upload_to='images/profil', verbose_name='photo de profil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='propriétaire du profil')),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils des utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
