# Generated by Django 4.2.9 on 2024-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='créé le'),
        ),
    ]
