# Generated by Django 4.2.9 on 2024-06-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='propriétaire du profil'),
        ),
    ]
